# Generated by Django 5.1.1 on 2024-10-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='item_profile_imgs/'),
        ),
    ]
