# Generated by Django 5.1.1 on 2024-10-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0010_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='item_profile_imgs/'),
        ),
    ]
