# Generated by Django 5.1.1 on 2024-10-06 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_text1', models.TextField()),
                ('body_text2', models.TextField(default='Hello')),
            ],
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_banner', models.CharField(max_length=100)),
                ('body_text1', models.CharField(max_length=100)),
                ('body_text2', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lrg_banner', models.ImageField(default='banners/default.jpg', upload_to='banners/')),
                ('lrg_banner_2', models.ImageField(default='banners/default.jpg', upload_to='banners/')),
                ('lrg_banner_3', models.ImageField(default='banners/default.jpg', upload_to='banners/')),
                ('body_text1_img', models.ImageField(default='banners/default.jpg', upload_to='banners/')),
                ('body_text2_img', models.ImageField(default='banners/default.jpg', upload_to='banners/')),
            ],
        ),
        migrations.CreateModel(
            name='PetProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('title', models.CharField(default='Sparky Needs A Title', max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('located', models.CharField(max_length=50)),
                ('pet_prof_img', models.ImageField(default='ppi/pet_default.jpg', upload_to='ppi/')),
                ('category', models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird')], default='other', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privacy_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TermsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_text', models.TextField()),
            ],
        ),
    ]
