# Generated by Django 5.1.1 on 2024-10-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='lrg_sponsor_img',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
    ]
