# Generated by Django 5.1.1 on 2024-10-07 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_homepage_lrg_sponsor_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='sponsor_01_img',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsor_02_img',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsor_03_img',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsor_04_img',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsor_05_img',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsor_06_img',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sponsor_07_img',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
    ]
